//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3
pub use sea_orm::{ActiveModelTrait, ColumnTrait, EntityTrait, QueryFilter, QuerySelect, Set};

pub use super::category::Entity as Category;
pub use super::comment::Entity as Comment;
pub use super::notification::Entity as Notification;
pub use super::post::Entity as Post;
pub use super::user::Entity as User;
