name: ci-frontend

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: frontend
    strategy:
      matrix:
        # You can add more, for any target you'd like!
        node-version:
          - 20.x
        os:
          - macOS-latest
          - windows-latest
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install

      - name: Build
        run: |
          npm run build --if-present
          npm run build
