name: ci-backend

on:
  push:
    # branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    # branches: [ main ]
    paths-ignore:
      - '**/README.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: backend
    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: stable
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
            toolchain: stable
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-gnu
            toolchain: stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        # Or @nightly if you want
        uses: dtolnay/rust-toolchain@v1
        # Arguments to pass in
        with:
          # Make Rust compile to our target (defined in the matrix)
          targets: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}

      - name: Build # bugs with working-directory see: https://github.com/actions-rs/cargo/issues/86
        run: |
          cargo build --verbose --release --target ${{ matrix.target }}
  
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: homeland-test
          POSTGRES_USER: "admin"
          POSTGRES_PASSWORD: "123456"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      REDIS_URL: redis://localhost:6379/1
      DATABASE_URL: postgres://admin:123456@localhost:5432/homeland-test
    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: cargo test --verbose