name: ci-backend

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: backend
    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: stable
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
            toolchain: stable
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-gnu
            toolchain: stable
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        # Or @nightly if you want
        uses: dtolnay/rust-toolchain@v1
        # Arguments to pass in
        with:
          # Make Rust compile to our target (defined in the matrix)
          targets: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}

      - name: Build # bugs with working-directory see: https://github.com/actions-rs/cargo/issues/86
        run: |
          cargo build --verbose --release --target ${{ matrix.target }}
