name: deploy

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**/README.md'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always
  RUST_BINARY_NAME: backend

permissions:
  contents: write

jobs:
  build-backend:
    name: build-backend
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: backend
    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: stable
          # - build: macos
          #   os: macos-latest
          #   target: x86_64-apple-darwin
          #   toolchain: stable
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-gnu
            toolchain: stable
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: get hash
        uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 6

      - name: get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}

      - name: Check Version
        run: |
          echo "short version hash => ${{ steps.short-sha.outputs.sha }}"
          echo "get-latest-tag ${{ steps.get-latest-tag.outputs.tag }}"

      - name: Install Rust
        # Or @nightly if you want
        uses: dtolnay/rust-toolchain@v1
        # Arguments to pass in
        with:
          # Make Rust compile to our target (defined in the matrix)
          targets: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}

      - name: Build # bugs with working-directory see: https://github.com/actions-rs/cargo/issues/86
        run: |
          cargo build --verbose --release --target ${{ matrix.target }}

      - name: Build archive
        shell: bash
        run: |
          # Replace with the name of your binary
          binary_name=${{ env.RUST_BINARY_NAME }}

          dirname="$binary_name-${{ steps.get-latest-tag.outputs.tag }}-${{ env.SHA }}-${{ matrix.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "target/${{ matrix.target }}/release/$binary_name.exe" "$dirname"
          else
            mv "target/${{ matrix.target }}/release/$binary_name" "$dirname"
          fi

          # add more resource to archive
          mv .env "$dirname"

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "$dirname.zip" "$dirname"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
            tar -czf "$dirname.tar.gz" "$dirname"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
          fi
      - name: Check Release archive
        run: |
          echo "release archive at: ${{ env.ASSET }}"

      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          retention-days: 5
          if-no-files-found: error
          path: backend/${{ env.ASSET }}

  archive:
    name: archive
    needs:
      - build-backend
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - name: download artifact backend
        uses: actions/download-artifact@v3
        with:
          name: backend-artifact
          path: ${{ github.workspace }}/backend/dist/

      - name: Display structure of downloaded files
        run: |
          ls -R ${{ github.workspace }}/backend/dist/

      - uses: softprops/action-gh-release@master
        name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          ## with permissions to create releases in the other repo
          token: "${{ secrets.GITHUB_TOKEN }}"
          #  body_path: ${{ github.workspace }}-CHANGELOG.txt
          prerelease: true
          # https://github.com/isaacs/node-glob
          files: |
            backend/dist/*.zip
            backend/dist/*.tar.gz