name: docker
on:
  push:
    # branches:
    #   - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build latest
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          # context: .
          push: true
          tags: |
            wuyuedefeng/homeland:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}